# Generated by Django 4.2.6 on 2023-10-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_created_date_alter_user_updated_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('pan', models.IntegerField(blank=True, null=True, unique=True)),
                ('vat', models.IntegerField(blank=True, null=True, unique=True)),
                ('phone_number', models.IntegerField(unique=True)),
            ],
        ),
    ]
