# Generated by Django 4.2.6 on 2023-10-10 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supplier_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.supplier'),
        ),
    ]
